"use client";

import "./globals.css";
import type { Metadata } from "next";

/* import axios from "axios";

axios.defaults.baseURL = import.meta.env.API_BASEURL || "http://localhost:3001"; */
import { Provider } from "react-redux";
import store from "../redux/store";

export const metadata: Metadata = {
  title: "Vibi",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={"font-normal flex flex-col bg-[#F7F8FA] justify-center m-auto text-[#102C57]"}>
          {children}
        </body>
      </Provider>
    </html>
  );
}
